---
apiVersion: v1
kind: Namespace
metadata:
  name: msrteamswebhook
  labels: 
    name: msrteamswebhook
---
# Create the Deployment resource
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msrteamswebhook
  namespace: msrteamswebhook
  labels:
    app: msrteamswebhook
    os: linux
    environment: dev
spec:
  selector:
    matchLabels:
      app: msrteamswebhook
  replicas: 1
  template:
    metadata:
      labels:
        app: msrteamswebhook
    spec:
      containers:
      - name: msrteamswebhook
        image: anubhavkul89/msteam-msr
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
        env:
        - name: ENVIRONMENT
          value: "dev"
---
# Create the Service resource
apiVersion: v1
kind: Service
metadata:
  name: msrteamswebhook-internal-svc
  namespace: msrteamswebhook
  labels:
    app: msrteamswebhook    
    os: linux
    environment: dev
spec:
  type: NodePort 
  selector:
     app: msrteamswebhook
  ports:
  - protocol: TCP
    port: 80
    nodePort: 32768 # default range is 32768-35535
    name: http



